backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "/_public/assets/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/img/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_src/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md {{year}}-{{month}}-{{day}}-
    fields: # The fields for each document, usually in front matter
      - {label: "Authors Layout", name: "layout", widget: "string", default: "blog_base.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Summary Description", name: "description", widget: "string"}
      - {label: "Meta Title (SEO)", name: "meta_title", widget: "string"}
      - {label: "Meta Description (SEO)", name: "meta_description", widget: "string"}
      - {label: "Author", name: "author", widget: "string", default: "Saeed Mirshekari"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", default: ["post"]}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      # - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}